### ISSUE TITLE
Single Consumers display higher consumption than the entire appartment

### ISSUE THREAD

**Issue by rlipperts** [DivineThreepwood/bcozy#96] opened 2019-08-13 12:19 UTC
Just a bug from bco-test --simulate? Bug in InfluxDBHandler? Bug in PowerTerminalDBService?

**Comment by DivineThreepwood** [comment] 2019-08-13 12:27
That's not a bug, it's a feature. Devices which are marked as "infrastructure" are not entailed in the consumption computation of their location. In the apartment most of the power sockets are marked as "infrastructure" which is changed by the end of the week. Please keep your test db up to date.

**Closed as completed** 2019-08-13 12:27 UTC
Labels: invalid
